import type { Metadata } from 'next';
import { LayoutHeader } from '@/app/Header';
import { cn } from '@/utils';
import { ProgressBar } from '@/components/ProgressBar';
import { ThemeProvider } from '@/components/ThemeProvider';

import './globals.css';
import React from 'react';
import { LayoutBreadcrumb } from './Breadcrumb';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning={true}>
      <body className={cn('ext-slate-500 dark:text-slate-400', 'antialiased t bg-background')}>
        <ThemeProvider attribute='class' defaultTheme='dark' enableSystem disableTransitionOnChange>
          <ProgressBar className='fixed top-0 h-[0.1rem] dark:bg-neutral-500 bg-neutral-700 z-[999]'>
            <div
              id='layout-header'
              className={cn(
                'w-screen',
                'backdrop-blur-sm',
                'bg-background/80',
                'sticky z-10 top-0'
              )}
            >
              <LayoutHeader />
              <LayoutBreadcrumb />
            </div>

            <main className={cn('min-h-screen')}>{children}</main>
            {/* <LayoutFooter /> */}
          </ProgressBar>
        </ThemeProvider>
      </body>
    </html>
  );
}
